"""
[RC1论文表格] export_rc1_params_table.py

从某个 run 的 logs/config_snapshot.json 导出论文用的参数表（LaTeX tabular）。

说明：
  - 不在脚本里写“论文用固定数值”；所有取值均来自 config_snapshot.json；
  - 输出表格附带“配置字段名”，便于追溯与复现。
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Tuple


def _fmt(v: Any) -> str:
    if v is None:
        return "-"
    if isinstance(v, bool):
        return "True" if v else "False"
    if isinstance(v, (int,)):
        return str(v)
    if isinstance(v, float):
        # Avoid over-long floats in paper
        return f"{v:.6g}"
    if isinstance(v, (tuple, list)):
        return "(" + ",".join(_fmt(x) for x in v) + ")"
    return str(v)


def _read_snapshot(run_dir: Path) -> Dict[str, Any]:
    p = run_dir / "logs" / "config_snapshot.json"
    if not p.exists():
        raise FileNotFoundError(f"Missing config snapshot: {p}")
    with p.open("r", encoding="utf-8") as f:
        return json.load(f)


def _pick(snapshot: Dict[str, Any], scope: str, key: str) -> Any:
    return (snapshot.get(scope) or {}).get(key)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-dir", type=str, required=True)
    ap.add_argument("--out-tex", type=str, required=True)
    args = ap.parse_args()

    run_dir = Path(args.run_dir).resolve()
    out_tex = Path(args.out_tex).resolve()
    out_tex.parent.mkdir(parents=True, exist_ok=True)

    snap = _read_snapshot(run_dir)

    # Rows: (category, symbol, meaning, unit, value, field)
    rows: List[Tuple[str, str, str, str, Any, str]] = [
        ("时隙", r"$\\Delta t$", "决策步长", "s", _pick(snap, "system_config", "DT"), "SystemConfig.DT"),
        ("时隙", r"$T$", "每回合最大步数", "step", _pick(snap, "system_config", "MAX_STEPS"), "SystemConfig.MAX_STEPS"),
        ("规模", r"$U$", "车辆数量", "-", _pick(snap, "system_config", "NUM_VEHICLES"), "SystemConfig.NUM_VEHICLES"),
        ("规模", r"$R$", "RSU数量", "-", _pick(snap, "system_config", "NUM_RSU"), "SystemConfig.NUM_RSU"),
        ("覆盖", r"$R_{\\mathrm{RSU}}$", "RSU覆盖半径", "m", _pick(snap, "system_config", "RSU_RANGE"), "SystemConfig.RSU_RANGE"),
        ("覆盖", r"$R_{\\mathrm{V2V}}$", "V2V覆盖半径", "m", _pick(snap, "system_config", "V2V_RANGE"), "SystemConfig.V2V_RANGE"),
        ("无线", r"$B$", "RB数量（V2I）", "-", _pick(snap, "system_config", "V2I_NUM_RB"), "SystemConfig.V2I_NUM_RB"),
        ("无线", r"$B$", "RB数量（V2V）", "-", _pick(snap, "system_config", "V2V_NUM_RB"), "SystemConfig.V2V_NUM_RB"),
        ("无线", r"$W_{\\mathrm{RB}}$", "RB带宽", "Hz", _pick(snap, "system_config", "V2I_RB_BW_HZ"), "SystemConfig.V2I_RB_BW_HZ"),
        ("无线", r"$N_0$", "噪声功率谱密度", "dBm/Hz", _pick(snap, "system_config", "NOISE_POWER_DENSITY_DBM"), "SystemConfig.NOISE_POWER_DENSITY_DBM"),
        ("DAG", r"$|\\mathcal{K}_u|$", "子任务数量范围", "-", (_pick(snap, "system_config", "MIN_NODES"), _pick(snap, "system_config", "MAX_NODES")), "SystemConfig.MIN_NODES/MAX_NODES"),
        ("DAG", r"$C_{u,k}$", "计算量范围（cycles）", "cycle", (_pick(snap, "system_config", "MIN_COMP"), _pick(snap, "system_config", "MAX_COMP")), "SystemConfig.MIN_COMP/MAX_COMP"),
        ("DAG", r"$D^{\\mathrm{in}}_{u,k}$", "输入数据量范围", "bit", (_pick(snap, "system_config", "MIN_DATA"), _pick(snap, "system_config", "MAX_DATA")), "SystemConfig.MIN_DATA/MAX_DATA"),
        ("DAG", r"$D_{u,i\\to k}$", "依赖边数据量范围", "bit", (_pick(snap, "system_config", "MIN_EDGE_DATA"), _pick(snap, "system_config", "MAX_EDGE_DATA")), "SystemConfig.MIN_EDGE_DATA/MAX_EDGE_DATA"),
        ("时限", r"$T_u^{\\mathrm{ddl}}$", "截止期模式", "-", _pick(snap, "system_config", "DEADLINE_MODE"), "SystemConfig.DEADLINE_MODE"),
        ("信誉", r"$p_m$", "恶意邻车比例", "-", _pick(snap, "system_config", "MALICIOUS_RATIO"), "SystemConfig.MALICIOUS_RATIO"),
        ("信誉", "-", "失败注入范围", "-", _pick(snap, "system_config", "TRUST_FAIL_SCOPE"), "SystemConfig.TRUST_FAIL_SCOPE"),
        ("训练", r"$\\gamma$", "折扣因子", "-", _pick(snap, "train_config", "GAMMA"), "TrainConfig.GAMMA"),
        ("训练", r"$\\lambda$", "GAE系数", "-", _pick(snap, "train_config", "GAE_LAMBDA"), "TrainConfig.GAE_LAMBDA"),
        ("训练", r"$\\epsilon$", "PPO截断系数", "-", _pick(snap, "train_config", "CLIP_PARAM"), "TrainConfig.CLIP_PARAM"),
        ("网络", "-", "EET边偏置", "-", _pick(snap, "train_config", "USE_EDGE_BIAS"), "TrainConfig.USE_EDGE_BIAS"),
        ("网络", "-", "EET空间偏置", "-", _pick(snap, "train_config", "USE_SPATIAL_BIAS"), "TrainConfig.USE_SPATIAL_BIAS"),
        ("网络", "-", "PBCA物理偏置", "-", _pick(snap, "train_config", "USE_PHYSICS_BIAS"), "TrainConfig.USE_PHYSICS_BIAS"),
    ]

    lines: List[str] = []
    lines.append("% Auto-generated by scripts/paper/export_rc1_params_table.py\n")
    lines.append("\\begin{tabular}{llllll}\n")
    lines.append("\\hline\n")
    lines.append("类别 & 符号 & 含义 & 单位 & 取值 & 配置字段 \\\\\n")
    lines.append("\\hline\n")
    for cat, sym, meaning, unit, val, field in rows:
        lines.append(f"{cat} & {sym} & {meaning} & {unit} & {_fmt(val)} & {field} \\\\\n")
    lines.append("\\hline\n")
    lines.append("\\end{tabular}\n")

    out_tex.write_text("".join(lines), encoding="utf-8")
    print(f"✓ Wrote: {out_tex}")


if __name__ == "__main__":
    main()

